site_name: ModelGauge
repo_url: https://github.com/mlcommons/modelgauge/
edit_uri: blob/main/docs/
theme:
  name: readthedocs
  highlightjs: false
plugins:
  - search
nav:
  - dev_quick_start.md
  - plugins.md
  - tutorial.md
  - tutorial_tests.md
  - tutorial_suts.md
  - prompt_response_tests.md
  - publishing.md