[tool.poetry]
name = "newhelm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
dacite = ">=1.6.0,<1.7.0"
zstandard = ">=0.18.0,<0.19.0"
tqdm = ">=4.64.1,<4.65.0"
types-tqdm = "^4.66.0.0"
demo_plugin = {path = "demo_plugin", optional = true, develop = true}
mmlu = {path = "mmlu", optional = true, develop = true}
helm_ports = {path = "helm_ports", optional = true, develop = true}
ridiculous_benchmark = {path = "ridiculous_benchmark", optional = true, develop = true}
bbq = {path = "bbq", optional = true, develop = true}

[tool.poetry.group.dev.dependencies]
pytest-datafiles = "^3.0.0"
pytest = "^7.4.3"
mypy = "^1.7.1"
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
demo = ["demo_plugin"]
helm_ports = ["helm_ports"]
bbq = ["bbq"]
all_supported_tests = ["mmlu"]
all_supported_benchmarks = ["ridiculous_benchmark"]
