[tool.poetry]
name = "modelgauge"
version = "0.3.3"
description = "Make it easy to automatically and uniformly measure the behavior of many AI Systems."
authors = ["MLCommons AI Safety <ai-safety-engineering@mlcommons.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
zstandard = ">=0.18.0,<0.19.0"
tqdm = ">=4.66.1"
types-tqdm = "^4.66.0.0"
pydantic = "^2.6.0"
sqlitedict = "^2.1.0"
gdown = ">=5.1.0"
demo_plugin = {path = "demo_plugin", develop = true, optional=true}
standard_tests = {path = "plugins/standard_tests", develop = true, optional=true}
modelgauge_openai = {path = "plugins/openai", develop = true, optional=true}
modelgauge_together = {path = "plugins/together", develop = true, optional=true}
modelgauge_huggingface = {path = "plugins/huggingface", develop = true, optional=true}
perspective_api = {path = "plugins/perspective_api", develop = true, optional=true}
tomli = "^2.0.1"
click = "^8.1.7"
typing-extensions = "^4.10.0"

[tool.poetry.group.dev.dependencies]
pytest-datafiles = "^3.0.0"
pytest = "^7.4.3"
mypy = "^1.7.1"
black = "^23.11.0"
pytest-mock = "^3.12.0"
pytest-timeout = "^2.3.1"

[tool.pytest.ini_options]
# Ignore the main source that might have things named "test"
addopts="--ignore=modelgauge/ --ignore=demo_plugin/modelgauge/ --ignore=plugins/*/modelgauge/"

[tool.mypy]
# Using namespace packages to do plugins requires us not to have __init__.py files.
# However, by default mypy uses those to map file paths to modules. This override fixes that.
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-explicit_package_bases
explicit_package_bases = true
mypy_path = "., demo_plugin, plugins/standard_tests, plugins/openai, plugins/huggingface, plugins/perspective_api, plugins/together"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
demo = ["demo_plugin"]
standard_tests = ["standard_tests"]
openai = ["modelgauge_openai"]
together = ["modelgauge_together"]
huggingface = ["modelgauge_huggingface"]
perspective_api = ["perspective_api"]
all_plugins = ["demo_plugin", "modelgauge_openai", "modelgauge_huggingface", "standard_tests", "perspective_api", "modelgauge_together"]

[[tool.poetry.source]]
name = "PyPI"

[[tool.poetry_bumpversion.replacements]]
files = ["demo_plugin/pyproject.toml", "plugins/huggingface/pyproject.toml", "plugins/openai/pyproject.toml", "plugins/perspective_api/pyproject.toml", "plugins/standard_tests/pyproject.toml", "plugins/together/pyproject.toml"]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.poetry.scripts]
modelgauge = "modelgauge.main:main"
