# Edit this file to add your secrets.

# This is an example of how to define a secret.
# The config is saying that within scope "demo" we have a
# key named "demo_api_key" that we are setting to value "12345".
[demo]
demo_api_key = "12345"
