name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: cache poetry install
      uses: actions/cache@v3
      id: cache-poetry
      with:
        path: ~/.local
        key: poetry-1.7.1-0
        
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: cache deps
      id: cache-deps  
      uses: actions/cache@v3
      with:
        path: .venv
        key: pydeps-${{ hashFiles('**/poetry.lock') }}

    
    - name: Install dependencies with caching
      run: poetry install --no-interaction --no-root
      if: steps.cache-deps.outputs.cache-hit != 'true'

    - name: Install the project
      run: poetry install --no-interaction

    - name: Lint formatting
      run: poetry run black --check .

    - name: Validate Poetry state
      run: poetry check

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest --ignore=plugins

    - name: Install with plugins
      run: poetry install --no-interaction --extras all_plugins

    - name: Run mypy
      run: poetry run mypy .

    - name: Test with plugin
      run: |
        source .venv/bin/activate
        pytest
